name: Deploy to Web3.Storage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: npm install 

      - name: Build Next.js site
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install Web3.Storage CLI
        run: npm install -g @web3-storage/w3cli

      - name: Authorize Web3
        run: w3 authorize lmunoz@cryptorepair.com

      # - name: Create web3 Space
      #   run: w3 space create app

      # - name: Validate web3 Space
      #   run: w3 space register
      - name: Deploy to web3
        run: w3 up public/dist/*
