name: Deploy to Web3.Storage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm install 

      - name: Build Next.js site
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install Web3.Storage CLI
        run: npm install web3.storage

      - name: Deploy to Web3.Storage
        run: web3.storage upload --token ${{ secrets.WEB3_STORAGE_TOKEN }} public dist/*

      - name: Set output variables
        id: outputs
        run: |
          echo "Web3.Storage CID: $(web3.storage info --output json)" >> $GITHUB_OUTPUT
